### PR TITLE
Add package.json for cordova 7

### LINKED ISSUE #35: package.json is missing
Unable to add the plugin due registry fail.

### PR DESCRIPTION
**Pull request by mzealey**
Fixes #35

### CODE REVIEW

**Comment by brodybits** [comment]
Will this be merged?

**Comment by mzealey** [comment]
I havn't seen any response to my 3 PRs from several months ago. Suggest you use https://github.com/mzealey/cordova-plugin-background-download repo instead.

**Comment by sgrebnov** [comment]
@mzealey thank you a lot for your contribution!

**Comment by sgrebnov** [comment]
@brodybits I plan to add some love to the plugin during next few days. Priority to make it fully working on iOS and Android (address issues).

**Pull request merged**
